-- DocTrack Security & Performance Overhaul
-- This file contains the final Row Level Security (RLS) policies applied to the database.
-- These were executed on the production Supabase project to enforce Zero Trust security.

-- ==========================================
-- 1. UTILITY FUNCTIONS (SECURITY DEFINER)
-- ==========================================
-- These functions bypass RLS to perform secure lookups without causing infinite recursion in policies.

CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS boolean
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.employees
    WHERE email = (auth.jwt() ->> 'email') AND role = 'Admin'
  );
$$;

CREATE OR REPLACE FUNCTION public.get_my_name()
RETURNS text
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT name
  FROM public.employees
  WHERE email = (auth.jwt() ->> 'email')
  LIMIT 1;
$$;


-- ==========================================
-- 2. DOCUMENTS TABLE POLICIES (DATA ISOLATION)
-- ==========================================

-- Remove any old permissive read policies
DROP POLICY IF EXISTS "Allow authenticated read" ON public.documents;

-- Enforce Data Privacy: Users only see their own documents, Admins see all
CREATE POLICY "Allow read own or admin" ON public.documents FOR SELECT TO authenticated USING (
  public.is_admin() OR holder = public.get_my_name()
);

-- Write/Update/Delete operations were previously restricted to Admins dynamically:
-- (e.g. WITH CHECK (public.is_admin()))


-- ==========================================
-- 3. EMPLOYEES TABLE POLICIES (PII ISOLATION)
-- ==========================================

-- Remove any old permissive read policies
DROP POLICY IF EXISTS "Allow authenticated read" ON public.employees;

-- Enforce Data Privacy: Users only see their own employee record, Admins see all
CREATE POLICY "Allow read own or admin" ON public.employees FOR SELECT TO authenticated USING (
  public.is_admin() OR email = (auth.jwt() ->> 'email')
);


-- ==========================================
-- 4. STORAGE BUCKET POLICIES (PRIVATE ATTACHMENTS)
-- ==========================================

-- Remove all public read/write access
DROP POLICY IF EXISTS "Public Read" ON storage.objects;
DROP POLICY IF EXISTS "Anon Insert" ON storage.objects;
DROP POLICY IF EXISTS "Anon Update" ON storage.objects;
DROP POLICY IF EXISTS "Anon Delete" ON storage.objects;

-- Authenticated users can read files (signed URLs generated by backend bypass this for specific files, but this ensures logged-in users can fetch their signed attachments)
CREATE POLICY "Allow authenticated read" ON storage.objects FOR SELECT TO authenticated USING (bucket_id = 'attachments');

-- Only Admins can upload, modify, or delete files
CREATE POLICY "Allow admin insert" ON storage.objects FOR INSERT TO authenticated WITH CHECK (
  bucket_id = 'attachments' AND public.is_admin()
);

CREATE POLICY "Allow admin update" ON storage.objects FOR UPDATE TO authenticated USING (
  bucket_id = 'attachments' AND public.is_admin()
);

CREATE POLICY "Allow admin delete" ON storage.objects FOR DELETE TO authenticated USING (
  bucket_id = 'attachments' AND public.is_admin()
);

-- Ensure the bucket itself is strictly private
-- UPDATE storage.buckets SET public = false WHERE id = 'attachments';
